### ISSUE TITLE
Split Apocryph Runtime into multiple Azure Functions applications

### ISSUE THREAD

**Issue by branimirangelov** [comrade-coop/apocryph#1]
Currently Apocryph Runtime is a single Azure Functions App, which complicates testing and continuous deployment.

**Comment by branimirangelov** [comment]
Also organize the streams in groups, rename accordingly

**Comment by bojidar-bg** [comment]
Organization of the source repo was initially started in 0c9a5f990788f4bdb270c81264f09e2af031d459 and continued with 8758adf48ab715e6f5c14b24c0353e408b60033f. Going forward, obsoleted by #7.
